import argparse
import collections
import collections.abc
import re

import parsing.parse_stubs
import parsing.sql_helpers

SQL_VERBOSE_FACTOR = 10 ** 7
TEMP_NAMESPACE_ID = 10
TEMP_NAMESPACE_PREFIX = 'Template:'

TempData = collections.namedtuple('TempData', ['temp_id', 'temp_title', 'page_id', 'page_title'])

def main():
	parser = argparse.ArgumentParser(description='Converts a templatelinks.sql file to a more readable, flexible form.')
	parser.add_argument('template_links_path', help='Path of the file giving all template links. This file (after decompression) is called "templatelinks.sql" in the database dumps.')
	parser.add_argument('link_targets_path', help='Path of the additional SQL file needed to parse template links. This file (after decompression) is called "linktarget.sql" in the database dumps.')
	parser.add_argument('stubs_path', help='Path of the CSV file containing stubs, as generated by parse_stubs.')
	parser.add_argument('output_path', help='Path of the CSV file to write the parsed templates to.')
	parser.add_argument('-v', '--verbose', action='store_true')
	args = parser.parse_args()

	parse_temps(**vars(args))

def parse_temps(template_links_path: str, link_targets_path: str, stubs_path: str, output_path: str, verbose: bool = False) -> None:
	if verbose:
		print('Reading stubs ...')
	stub_master = parsing.parse_stubs.StubMaster(stubs_path)

	if verbose:
		print(f'Reading link targets:')
	link_targets_to_temp_titles = {}
	for link_target in parsing.sql_helpers.parse_sql(link_targets_path, verbose):
		if link_target[1] == TEMP_NAMESPACE_ID:
			link_targets_to_temp_titles[link_target[0]] = link_target[2].replace('_', ' ')

	if verbose:
		print(f'Loaded {len(link_targets_to_temp_titles)} temp titles.')
		print('Processing template links:')
	missing_temps = set()
	with open(output_path, 'w', encoding='utf-8') as out_file:
		for link in parsing.sql_helpers.parse_sql(template_links_path, verbose):
			page_id = link[0]
			target_id = link[2]
			try:
				temp_title = link_targets_to_temp_titles[target_id]
			except KeyError:
				# Not a template
				continue
			if temp_title.startswith('tracking/'):
				continue
			try:
				temp_id = stub_master.id(temp_title, TEMP_NAMESPACE_ID)
			except KeyError:
				if temp_title not in missing_temps:
					print(f'Warning: {TEMP_NAMESPACE_PREFIX}{temp_title} is transcluded but does not exist.')
					missing_temps.add(temp_title)
				continue
			try:
				page_title = stub_master.title(page_id)
			except KeyError:
				# I found this occurred many times in the 24-07-01 dump.
				continue
			print(f'{temp_id}|{temp_title}|{page_id}|{page_title}', file=out_file)

def temps_gen(templates_path: str) -> collections.abc.Iterator[TempData]:
	with open(templates_path, encoding='utf-8') as temps_file:
		for line in temps_file:
			fields = (line[:-1].split('|', maxsplit=3))
			yield TempData(temp_id=int(fields[0]), temp_title=fields[1], page_id=int(fields[2]), page_title=fields[3])

if __name__ == '__main__':
	main()
