import argparse
import collections
import collections.abc
import re

import parsing.parse_stubs
import parsing.sql_helpers

# Master refers to CategoryMaster
CAT_MASTER_VERBOSE_FACTOR = 10 ** 6
WRITING_VERBOSE_FACTOR = 10 ** 5
# The MediaWiki category namespace ID
CAT_NAMESPACE_ID = 14

CatLink = collections.namedtuple('CatLink', ['cat_id', 'cat_title', 'page_id', 'page_ns', 'page_title'])

def main():
	parser = argparse.ArgumentParser(description='Converts a categorylinks.sql file to a more readable, flexible form.')
	parser.add_argument('sql_path', help='Path of the SQL file giving all category associations. This file (after it is unzipped) is called "categorylinks.sql" in the database dumps.')
	parser.add_argument('stubs_path', help='Path of the CSV file containing page ids, namespaces, and titles, generated by parse_stubs.py.')
	parser.add_argument('link_targets_path', help='Path of the SQL file containing link target data. This file (after it is unzipped) is called "linktarget.sql" in the database dumps.')
	parser.add_argument('output_path', help='Path of the CSV file to write the parsed categories to.')
	parser.add_argument('-v', '--verbose', action='store_true')
	args = parser.parse_args()

	parse_cats(**vars(args))

def parse_cats(sql_path: str, stubs_path: str, link_targets_path: str, output_path: str, verbose: bool = False) -> None:
	'''The way in which stubs, link targets, and category links are retrieved is intentionally designed to limit memory usage. First we read in the basic info of each category link (the category's link target and the page ID). Then we read stubs into memory (since there are fewer stubs than link targets or category links). There are more link targets than anything else, so we avoid ever having them all in memory by read linearly though them as we write the category links out. This means the order of the category links is not preserved, and is dictated by the order of the link targets.'''
	basic_cat_links: dict[int, list] = collections.defaultdict(list)
	if verbose:
		print('Reading category links (SQL):')
	for row in parsing.sql_helpers.parse_sql(sql_path, verbose):
		# Keys are link target IDs for the category and values are page IDs
		basic_cat_links[row[6]].append(row[0])

	if verbose:
		print('Reading stubs...')
	stub_master = parsing.parse_stubs.StubMaster(stubs_path)
	if verbose:
		print(f'Read {len(stub_master)} stubs.')

	if verbose:
		print('Reading link targets and writing category links:')
	with open(output_path, 'w', encoding='utf-8') as out_file:
		for count, row in enumerate(parsing.sql_helpers.parse_sql(link_targets_path, verbose)):
			if verbose and count % WRITING_VERBOSE_FACTOR == 0:
				print(f'{count:,}')

			if row[0] not in basic_cat_links:
				continue

			cat_title = row[2].replace('_', ' ')
			try:
				cat_id = stub_master.id(cat_title, CAT_NAMESPACE_ID)
			except KeyError:
				# A category may not be found if it is in use but has no page
				continue
			for page_id in basic_cat_links[row[0]]:
				try:
					page_ns = stub_master.ns(page_id)
					page_title = stub_master.title(page_id)
				except KeyError:
					print(f'Warning: A category link exists putting page ID {page_id} in Category:{cat_title}, but no such page exists. Skipping.')
					continue
				out_file.write(f'{cat_id}|{cat_title}|{page_id}|{page_ns}|{page_title}\n')

def cats_gen(categories_path: str) -> collections.abc.Iterator[CatLink]:
	with open(categories_path, encoding='utf-8') as cats_file:
		for line in cats_file:
			cat_id, cat_title, page_id, page_ns, page_title = (line[:-1].split('|', 4))
			yield CatLink(int(cat_id), cat_title, int(page_id), int(page_ns), page_title)

class Cat():
	def __init__(self):
		# Maps page IDs of subcategories to their titles
		self.subcats: dict[int, str] = {}
		self.pages: set[parsing.parse_stubs.Stub] = set()

	def __str__(self) -> str:
		return f'Category ({len(self.subcats)} subcategories and {len(self.pages)} pages)'

class CategoryMaster():
	def __init__(self, categories_path: str, verbose: bool = False):
		if verbose:
			print('Loading all categories:')
		self.cats: dict[int, Cat] = collections.defaultdict(Cat)
		for count, cat_link in enumerate(cats_gen(categories_path)):
			if verbose and count % CAT_MASTER_VERBOSE_FACTOR == 0:
				print(f'{count:,}')

			if cat_link.page_ns == CAT_NAMESPACE_ID:
				self.cats[cat_link.cat_id].subcats[cat_link.page_id] = cat_link.page_title
			else:
				self.cats[cat_link.cat_id].pages.add(parsing.parse_stubs.Stub(cat_link.page_id, cat_link.page_ns, cat_link.page_title))

	def subcats(self, cat_id: int, titles: bool = False) -> set[int] | set[str]:
		if titles:
			return set(self.cats[cat_id].subcats.values())
		else:
			return set(self.cats[cat_id].subcats.keys())

	def pages(self, cat_id: int, titles: bool = False) -> set[int] | set[str]:
		if titles:
			return {stub.title for stub in self.cats[cat_id].pages}
		else:
			return {stub.id for stub in self.cats[cat_id].pages}

	def descendant_cats(self, cat_id: int, max_depth: int = -1) -> set[int]:
		des_cats = {cat_id}
		# Purposefully continue if max_depth is negative
		if max_depth != 0:
			for subcat in self.subcats(cat_id):
				des_cats |= self.descendant_cats(subcat, max_depth - 1)
		return des_cats

	def descendant_pages(self, cat_id: int, titles: bool = False, max_depth: int = -1) -> set[int] | set[str]:
		des_pages: set[int] | set[str] = set()
		for cat_id in self.descendant_cats(cat_id, max_depth):
			des_pages |= self.pages(cat_id, titles=titles)
		return des_pages

	def __len__(self) -> int:
		return len(self.cats)

	def __iter__(self) -> collections.abc.Iterator[tuple[int, Cat]]:
		return self.cats.items()

if __name__ == '__main__':
	main()
